// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAa2v8mMVQDZ9FrWa7C54KsGjwrxXg48aE',
    appId: '1:435266360030:ios:ef5e61a9924ea7d8f0a84f',
    messagingSenderId: '435266360030',
    projectId: 'vocalnova-169b2',
    storageBucket: 'vocalnova-169b2.firebasestorage.app',
    iosBundleId: 'com.example.vocalnova',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAa2v8mMVQDZ9FrWa7C54KsGjwrxXg48aE',
    appId: '1:435266360030:ios:ef5e61a9924ea7d8f0a84f',
    messagingSenderId: '435266360030',
    projectId: 'vocalnova-169b2',
    storageBucket: 'vocalnova-169b2.firebasestorage.app',
    iosBundleId: 'com.example.vocalnova',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBE0JDSpxwQGX-yW-QwtZzxJnY7sIT7qRs',
    appId: '1:435266360030:web:362a8f379794f5cff0a84f',
    messagingSenderId: '435266360030',
    projectId: 'vocalnova-169b2',
    authDomain: 'vocalnova-169b2.firebaseapp.com',
    storageBucket: 'vocalnova-169b2.firebasestorage.app',
    measurementId: 'G-J28F0LPTQN',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBE0JDSpxwQGX-yW-QwtZzxJnY7sIT7qRs',
    appId: '1:435266360030:web:362a8f379794f5cff0a84f',
    messagingSenderId: '435266360030',
    projectId: 'vocalnova-169b2',
    authDomain: 'vocalnova-169b2.firebaseapp.com',
    storageBucket: 'vocalnova-169b2.firebasestorage.app',
    measurementId: 'G-J28F0LPTQN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJJHzISybAW0ECMyCSmskAti2CLD7-QsA',
    appId: '1:435266360030:android:5ebbb821418fd12df0a84f',
    messagingSenderId: '435266360030',
    projectId: 'vocalnova-169b2',
    storageBucket: 'vocalnova-169b2.firebasestorage.app',
  );

}